sonar.projectKey=python-devops-demo
sonar.projectName=python-devops-demo

sonar.sources=.

sonar.host.url=http://192.168.47.129:9000

sonar.login=squ_8d38b3f27407c13006dba7685110ee544410ce31
sonar.scanner.skipSystemTruststore=true
sonar.analysisCache.enabled=false

sonar.exclusions=**/__pycache__/**,**/*.pyc
sonar.python.coverage.reportPaths=coverage.xml
